### ISSUE TITLE
Current version is broken

### ISSUE THREAD

**Issue by admiralspeedy** [ppkantorski/libultrahand#3] opened 2024-11-01 07:22 UTC
Starting with commit 8300690f475105ef1325f8fc27ab26fccc5f1645, I am unable to properly build overlays using libultrahand.

The issue is twofold:

1) Changes were made incorrectly related to disabling fstream and if you try to disable it as described in the readme, you get an error about "newLine" not being declared. The if statement is done wrong and results in "newLine" never being declared if you disable fstream.

2) I get a huge number of errors related to tesla.cpp when trying to build an overlay such as EdiZon-Overlay. It tells me "Renderer" and "cfg" (and many others) are not declared, and it tells me there are many invalid uses of "this" in non-member functions.

**Comment by ppkantorski** [comment] 2024-11-02 01:06
hmm let me do some tests.  i'll look into it

**Comment by ppkantorski** [comment] 2024-11-02 01:55
Ok everything should be fixed now.

**Comment by ppkantorski** [comment] 2024-11-02 02:00
Ah edizon having some issues.  let me resolve them.

**Comment by ppkantorski** [comment] 2024-11-02 02:27
Yeah i just forgot to remove a file that shouldnt have been there (tesla.cpp).  It should all be good now.

**Comment by admiralspeedy** [comment] 2024-11-02 02:31
Awesome, thanks!

Out of curiosity, how did Ultrahand Overlay build with these issues? Wouldn't it have failed?

**Comment by ppkantorski** [comment] 2024-11-02 02:50
The issue is wiithin the Makefile.  EdiZon has `libs/libultrahand/libtesla/source` added (which is usually empty / does not exist).  But I was playing with that folder a little bit before during my testing (which is why `tesla.cpp` was still there).  That line should probably be removed from the Makefile since everything for tesla is in the `tesla.hpp` file.  Before I was trying to see if i could optimize `tesla.hpp` a bit more by splitting stuff into a separate `tesla.cpp`, but I decided it was unnecessary.  Ultrahand does not include `libtesla/source` in `SOURCES` so it did not have any issues.

As for the other reason, Ultrahand does not use the NO_FSTREAM directive, so those commands using `stdio.h` (where the `newLine` bug was) did not apply to building Ultrahand.

**Closed as completed** 2024-11-02 06:40 UTC
